name: vosk_flutter_service_example
description: Demonstrates how to use the vosk_flutter plugin.

publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  file_picker: ^10.3.8
  flutter:
    sdk: flutter

  path_provider: ^2.1.5
  record: ^6.0.0
  vosk_flutter_service:
    path: ../
  wav: ^1.2.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  path: any
flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/models/
