name: vosk_flutter_service
description: Flutter plugin for offline speech recognition using the Vosk speech recognition toolkit.
version: 0.0.2
homepage: https://bechattaoui.dev/
repository: https://github.com/dhia-bechattaoui/vosk-flutter-service

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

topics:
  - speech-recognition
  - offline-speech
  - vosk
  - voice-control
  - ai

funding:
  - https://github.com/sponsors/Dhia-Bechattaoui

dependencies:
  archive: ^4.0.7
  args: ^2.5.0
  build_cli_annotations: ^2.1.0
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.2.2
  package_config: ^2.1.0
  path: ^1.9.0
  path_provider: ^2.1.4
  permission_handler: ^12.0.1
  pubspec_parse: ^1.3.0

dev_dependencies:
  build_cli: ^2.2.3
  build_runner: ^2.4.12
  ffigen: ^20.1.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

ffigen:
  name: VoskLibrary
  output: 'lib/src/generated_vosk_bindings.dart'
  headers:
    entry-points:
      - 'vosk-api/src/vosk_api.h'

flutter:
  plugin:
    platforms:
      android:
        package: org.vosk.vosk_flutter
        pluginClass: VoskFlutterPlugin
      ios:
        pluginClass: VoskFlutterPlugin
      linux:
        pluginClass: VoskFlutterPlugin
        ffiPlugin: true
      macos:
        pluginClass: VoskFlutterPlugin
        ffiPlugin: true
      windows:
        pluginClass: VoskFlutterPlugin
        ffiPlugin: true
